# action.yml
name: 'Fog Report'
author: Arjen Schwarz
description: 'Generate a fog report for your CloudFormation deployment'
inputs:
  stackname:
    description: 'The name of the CloudFormation stack'
    required: true
    default: 'your-stack'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.stackname }}
branding:
  icon: cloud-snow
  color: orange